### ISSUE TITLE
Without the form-group class the parent input field is removed

### ISSUE THREAD

**Issue by mesnitu** [rogeriotaques/valida#2]
Hi
Great plugin, easy to use.
In the plugin wiki, the html doesn't seen to be very important, but without the form-group class around the input text field, the parent input is removed.
No sure if this is made for bootstrap, and works out of the box for it, but this doesn't work : 

```
<label></label>
<input type="text">
```

This is ok: 

```
<label></label>
<whatever class="form-group">
<input type="text">
</whatever>
```

Input type text it's the only thing I need. Didn't check the checkboxes. 
But perhaps it would be nice to provide this info. 

Best Regards

**Comment by mesnitu** [comment]
`el.siblings('.form-control-feedback, .at-error, .at-warning, .at-info, .at-success').remove();`

**Comment by rogeriotaques** [comment]
Hello @mesnitu!

Thanks for your comment! Well, you're right!

From version 2.0 this plugin was totally rewritten to support bootstrap, and probably that's why it's not working well when you use it without using bootstrap as well.

Prior to version 2.0, I'm pretty sure that Valida was working well for non bootstrap forms. Basically, on that time the source code was hosted on Google Codes, and you still can get the older versions from there, even nowadays.

Here's the deprecated repository address:
https://code.google.com/archive/p/jquery-valida/downloads

In anyway, you can help me to improve this plugin if you have time. Please do whatever changes you think necessary and let me know thru a pull request. :) 

Roger.
